version: '3.8'
services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
volumes:
  ollama_data:
